### ISSUE TITLE
How can you make sure each pixel has its corresponding point cloud?

### ISSUE THREAD

**Issue by Loydian** [apple/ml-pgdvs#5]
Since the point clouds are filtered by a cycle consistent check, how do you inpaint the filtered points?

**Comment by Xiaoming-Zhao** [comment]
I think I understand your question clearly now: previously I thought you asked about how we can have corresponding point clouds for **pixels in the source images**. However, it seems like you actually ask about **target pixels**.

Let me clarify one thing:
- for **static** rendering, since we rely on GNT, we start from a specific pixel in the target rendering, cast a ray, sample points on the ray, and query the GNT model.
- for the **dynamic** rendering, we do not start from the target pixel. Instead, we start from the temporally closest source images, obtain point clouds for source images, interpolate them to get a point cloud for the target time, and then directly render the point cloud with the target pose.

Essentially, for dynamic rendering, we do not need to "make sure each pixel has its corresponding point cloud".

**Comment by Loydian** [comment]
Is that mean "after project dynamic point cloud to target view, the rest of the images are rendered by GNT model"?

**Comment by Xiaoming-Zhao** [comment]
Yes, you are right. I hope the following schematics can provide you a better sense.

<img width="2151" alt="rendering" src="https://github.com/user-attachments/assets/0e17c493-1423-4c72-9c5f-be2092376520">
